DATA:
  dataset: multi
  data_root: datasets/ensemble_dataset/ 
  wav_path: wav
  vertices_path: npz
  template_file: generic_model.pkl
  train_subjects: English 

NETWORK:
  arch: stage2interactive
  in_dim: 15125
  hidden_size: 1024
  num_hidden_layers: 6
  num_attention_heads: 8
  intermediate_size: 1536
  window_size: 1
  quant_factor: 0
  face_quan_num: 16
  neg: 0.2
  autoencoder: stage1_vocaset
  INaffine: False
  style_emb_method: nnemb # onehot or nnemb
  interactive_window: 50 # Number of frames to be used for interactive window
  hop_length: 640 # Number of audio samples per frame in your data
  
VQuantizer:
  n_embed: 256
  zquant_dim: 64

PREDICTOR:
  feature_dim: 1024
  vertice_dim: 15125
  device: cuda
  period: 25
  vqvae_pretrained_path: /root/Projects/fasttalk/checkpoints/s1_model.pth.tar
  wav2vec2model_path: facebook/wav2vec2-large-xlsr-53 
  teacher_forcing: True
  num_layers: 6
  n_head: 4 

DEMO:
  model_path: /root/Projects/fasttalk/checkpoints/s2_model.pth.tar 
  condition: English
  subject: id
  demo_wav_dir_path: demo/input/
  demo_output_path: demo/output/
  fps: 25
  background_black: True 